services:
  mysql:
    image: mysql
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: jobify
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db:
